language: bash

sudo: required

services:
- docker

script:
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  make deploy; else echo ">>> Could not perform deploy"; fi   