//Errors
export const GET_ERRORS = "GET_ERRORS";

//User
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Project
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT"; 

//Layout
export const CLOSE_PROJECT_DETAIL_SIDEBAR = "CLOSE_PROJECT_DETAIL_SIDEBAR";
export const OPEN_PROJECT_DETAIL_SIDEBAR = "OPEN_PROJECT_DETAIL_SIDEBAR";
export const TOGGLE_NAVIGATION_SIDEBAR = "TOGGLE_NAVIGATION_SIDEBAR";