//Errors
export const GET_ERRORS = "GET_ERRORS";

//User
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Layout
export const CLOSE_PROJECT_DETAIL_SIDEBAR = "CLOSE_PROJECT_DETAIL_SIDEBAR";
export const OPEN_PROJECT_DETAIL_SIDEBAR = "OPEN_PROJECT_DETAIL_SIDEBAR";
export const TOGGLE_NAVIGATION_SIDEBAR = "TOGGLE_NAVIGATION_SIDEBAR";
export const OPEN_ISSUE_DETAILS_MODAL = "OPEN_ISSUE_DETAILS_MODAL";
export const CLOSE_ISSUE_DETAILS_MODAL = "CLOSE_ISSUE_DETAILS_MODAL";

//Project
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT"; 

//Kanban Categories
export const KANBAN_CATEGORIES_LOADING = "KANBAN_CATEGORIES_LOADING";
export const GET_KANBAN_CATEGORIES = "GET_KANBAN_CATEGORIES";
export const CREATE_KANBAN_CATEGORY = "CREATE_KANBAN_CATEGORY";
export const DELETE_KANBAN_CATEGORY = "DELETE_KANBAN_CATEGORY";
export const UPDATE_KANBAN_CATEGORY = "UPDATE_KANBAN_CATEGORY";
export const REARANGE_KANBAN_BOARD = "REARANGE_KANBAN_BOARD";

//Kanban cards
export const DELETE_CARD = "DELETE_CARD";
export const CREATE_CARD = "CREATE_CARD";
export const UPDATE_CARD = "UPDATE_CARD";

//Settings
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const GET_SETTINGS = "GET_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";